services:
  nexusflow-db:
    image: postgres:17-alpine
    container_name: nexusflow-auth-db
    environment:
      POSTGRES_DB: nexusflow_auth
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
    ports:
      - "5433:5432"
    networks:
      - nexus-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: nexusflow-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nexusflow.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - nexus-network
    depends_on:
      - nexusflow-db

  kafka:
      image: apache/kafka:latest
      container_name: nexusflow-kafka
      ports:
        - "9092:9092"
      environment:
        # Configurações KRaft para imagem Apache
        - KAFKA_NODE_ID=1
        - KAFKA_PROCESS_ROLES=broker,controller
        - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
        - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
        - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
        - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
        - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
        - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      networks:
        - nexus-network

networks:
  nexus-network:
    driver: bridge